### PR TITLE
✨ feat(codelens): add CodeLens provider for playing sounds

### PR DESCRIPTION
**Pull request by RobertFrydenlund**
Added ability to preview sounds.

### CODE REVIEW

**Comment by thmsndk** [comment]
Thanks for the PR! I presume you are the one I talked with earlier today :D

Sadly the playing of the sound does not seem to work for me when testing it out, when I press the `Play sound` code lens all that happens is a `console.log(err)` where the value is 1
Sadly that error message is not particular useful in trying to figure out why the sounds is not playing, I presume it is because I don't have one of the default available audio players.

Now about the actual code, firstly, we should be using import, and not require. I assume DefinatelyTyped has the types for play-sound if we can get that library to work for everyone out of the box. The types should be here https://www.npmjs.com/package/@types/play-sound and can be added as a dev dependency.

Things I'd like to improve once we are sure the playback works for as many people as possible.
- Adding all 16 numeric sound files
- Adding the Shaper sound files (`ShAlchemy|ShBlessed|ShChaos|ShDivine|ShExalted|ShFusing|ShGeneral|ShMirror|ShRegal|ShVaal`)
- Add support for PlayAlertSoundPositional
- Add support for CustomAlertSound and CustomAlertSoundOptional
- Adjust the volume depending on the volume setting for the command

**Comment by thmsndk** [comment]
I've "kinda" fixed the code, it opens up mediaplayer, and it feels a little clunky, perhaps we need to supply some more options.
image

**Comment by RobertFrydenlund** [comment]
Ah, that is not intended, on my setup it plays the sound in the background as it should. Unfortunately I don't have a windows setup available right now :penguin:. Maybe something like this would work better? This is the default list, I just dropped `mplayer`.

`const player = Player({
    players: [
      "afplay",
      "mpg123",
      "mpg321",
      "play",
      "omxplayer",
      "aplay",
      "cmdmp3",
      "cvlc",
      "powershell",
    ],
  });`

**Comment by RobertFrydenlund** [comment]
Hi again, it was indeed me you spoke with earlier :)

I'm not a huge fan of bundling binaries, but this seems to be the approach used in other vs code extensions to play sound. I do not have a Windows environment available at the moment, so I cant really test any of these changes :penguin:

**Comment by thmsndk** [comment]
Yeah definitely not a fan of bundling a random .exe file, I don't want to do that.

I have a change where I've tried executing the player ourself, basically the same as play-sound did, I've experimented with different ways to get PowerShell to run in the background, but I had no success. I can commit my change, and then I think we should just add it as a known limitation for windows, perhaps suggesting installing another media player that supports cli / background playing.

**Comment by thmsndk** [comment]
I tried one last thing, with the help of AI :) and I seem to have gotten it to work, the sound played at least :D
image

**Comment by RobertFrydenlund** [comment]
I was playing with the idea of using PowerShell as well, but I was unsure how the default script execution policy would handle it. It still works great on linux though, so looks good to me :)

**Comment by thmsndk** [comment]
@RobertFrydenlund Could I perhaps persuade you to make the other changes supporting all the sound methods?

**Comment by RobertFrydenlund** [comment]
Looking into it.

**Comment by thmsndk** [comment]
Awesome, I gave it a quick test, the default files seems to work great.

I think when playing  custom sounds we need to do it relatively to where the .filter file is located.
image
I'm editing a .filter file from my downloads folder that is not part of the workspace

There is a gold.wav next to it as you can see there is no validation error about a missing file.
image

Also not seeing any output in the debug console.

Also perhaps the codelens could say `Play {sound-file-name.extension}` instead?

**Comment by thmsndk** [comment]
That works great!, the only thing I can think of is perhaps to hide the CodeLens if the file does not exist.
image

**Comment by thmsndk** [comment]
@RobertFrydenlund I feel this PR is ready to merge. Do you want me to mention you in the readme / changelog for the feature? :)

**Comment by RobertFrydenlund** [comment]
I would appreciate that a lot! :)

**Comment by thmsndk** [comment]
Should I write something else than [RobertFrydenlund](https://github.com/RobertFrydenlund) with a link to your github?

**Comment by RobertFrydenlund** [comment]
Just a link to my github will be fine, I rarely mix socials.

**Pull request merged**
